In [ ]:
import numpy as np

In [ ]:
# One dimension array
a = np.array([[1,2,3,4,5]], dtype="int8" )

In [ ]:
print("Type of Array a is", type(a))
print("Shape of A is",a.shape)
print("Dimensions of A is", a.ndim)

In [ ]:
# Two Dimension Array
b = np.array([
                 [1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15]   
                ], dtype = 'int16')

In [ ]:
print("Type of Array b is", type(b))
print("Data type of Array a is", a.dtype)
print("Shape of b is",b.shape)
print("Dimensions of b is", b.ndim)

In [ ]:
print("Each item size is",b.itemsize)
print("Total number of elements is", b.size)
print("Total size of the array is", b.nbytes)

In [ ]:
# Providing a jump value for the array selection. Minus is for backward selection
b[1, : : -2]

In [ ]:
# Array of 0s
zero = np.zeros((3,3,3), dtype= "int16")
zero

In [ ]:
# Creating an array with only 1s
ones = np.ones((2,2),dtype="int16")
ones

In [ ]:
# Filling an array with only one number 
full_fours = np.full((3,3),4)
full_fours

In [ ]:
full_like_ones = np.full_like(ones,5)
full_like_ones

In [ ]:
# Creating an array with random numbers and converting the type
random_array = np.round(np.random.rand(4,3)*1000)
random_array = random_array.astype("int16")
print("Size of the array is",random_array.nbytes)

In [ ]:
# Creating an array with random numbers with the shape of an existing array
np.random.random_sample(a.shape)

In [ ]:
# Creating an array with Integers
np.random.randint(133, 184, size = (5,2))

In [ ]:
# Creating an identity matrix
identity_mat = np.identity(5)
identity_mat.astype("int")

In [ ]:
cp = np.copy(a)
cp

In [ ]:
special_task = np.ones((5,5))
special_task = special_task.astype("int")
special_task_sub = np.zeros((3,3))
special_task_sub[1,1] = 9
special_task_sub = special_task_sub.astype("int")
print(special_task,"\n \n \n ")
print(special_task_sub, "\n \n \n")
special_task[1:-1, 1:-1] = special_task_sub
print(special_task)

In [ ]:
rep = np.array([[1,2,3]])
rep_new = np.repeat(rep,3,axis=0)
rep_new

##### Copying Arrays 

In [ ]:
# To copy the values and not the memory locations of an array 
copy_new = rep_new.copy()

##### Mathematical expressions

In [ ]:
print(a,"\n\n",b)

In [ ]:
a.append[1,0:5] = [6,7,8,9,10]

In [ ]:
np.append(a,[[6,7,8,9,10]],axis=0)

In [ ]:
a = np.array([[1,2],
              [3,4]])
b=np.array([[10,20],
            [30,40]])

In [ ]:
# Actual matrix multiplication
a.dot(b)

In [ ]:
a= a.astype("int8")

In [ ]:
task2 = np.arange(25).reshape(5,5)
task2

In [ ]:
task2ans = task2[1: :2 , 0: :2]
task2ans

In [38]:
a = np.arange(0,80,10)

In [ ]:
indices = [1,2,-1]
b=a[indices]
b

In [ ]:
mask = np.random.randint(0,2, size = (a.shape), dtype=bool)
mask

In [ ]:
a[mask]

In [43]:
a = a.reshape(8,1)
a

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70]])

In [46]:
b = np.array([1,2])
b

array([1, 2])

In [48]:
b + a

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72]])